// traces_to: L2-007
export const ICON_ALIASES: Record<string, string> = {
  contacts: 'person',
  partners: 'domain',
  tags: 'sell',
  notes: 'sticky_note_2',
  kanban: 'view_kanban',
  ideas: 'lightbulb',
  events: 'event',
  calendar: 'calendar_month',
  locations: 'location_on',
  search: 'search',
  filter: 'filter_list',
  sort: 'swap_vert',
  settings: 'settings',
  profile: 'account_circle',
  'sign-out': 'logout',
  add: 'add',
  edit: 'edit',
  delete: 'delete',
  archive: 'archive',
  restore: 'unarchive',
  close: 'close',
  back: 'arrow_back',
  forward: 'arrow_forward',
  up: 'expand_less',
  down: 'expand_more',
  menu: 'menu',
  more: 'more_vert',
  success: 'check_circle',
  error: 'error',
  warning: 'warning',
  info: 'info',
  help: 'help',
  'visibility-on': 'visibility',
  'visibility-off': 'visibility_off',
  'drag-handle': 'drag_indicator',
};

export type IconAlias = keyof typeof ICON_ALIASES;
export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
