@startuml
!include <C4/C4_Component>
LAYOUT_WITH_LEGEND()
title Target components - Share detail links
Container_Boundary(browser, "Frontend - Upper Room") {
Component(f0, "TarShareButton", "Angular type", "Feature presentation or client behavior")
Component(f1, "ContactDetail", "Angular type", "Feature presentation or client behavior")
}
Rel(f0, f1, "Target collaboration")

@enduml
