@startuml
!include <C4/C4_Component>
LAYOUT_WITH_LEGEND()
title Target components - Navigate application
Container_Boundary(browser, "Frontend - Upper Room") {
Component(f0, "AppShell", "Angular type", "Feature presentation or client behavior")
Component(f1, "Crumb", "Angular type", "Feature presentation or client behavior")
Component(f2, "TarDrawer", "Angular type", "Feature presentation or client behavior")
}
Rel(f0, f1, "Target collaboration")
Rel(f0, f2, "Target collaboration")

@enduml
